config/routes.rb
Rails.application.routes.draw do

  get 'users/login' => 'sessions#new'
  post 'users/login' => 'sessions#create'
  delete 'users/logout' => 'sessions#destroy'
  get 'users/new' => 'users#new'
  post 'users/new' => 'users#create'
  post 'recipes/:id' => 'recipe_plans#create', as: 'recipe_plans'
  get 'suggestion' => 'suggestions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes do
    get :autocomplete_recipe_name, :on => :collection
  end
  resources :shopping_lists, only: [:index, :show, :create]
  resources :plans, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipe_plans, only: [:create, :destroy]
  get "/", to: 'home#index'

  resources :ingredients, only: [:index, :show] do
    get :autocomplete_ingredient_name, :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_one :shopping_list
  has_many :recipe_plans
  has_many :recipes, through: :recipe_plans
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_plans
  has_many :plans, through: :recipe_plans

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe_plan.rb
class RecipePlan < ApplicationRecord
  belongs_to :plan
  belongs_to :recipe
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :plans
  has_many :shopping_lists
  validates :name, uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  autocomplete :ingredient, :name, :full => true

  def index
    @ingredients = Ingredient.new
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = current_user.plans.all
  end

  def show
    @my_plan = current_user.plans.find(params[:id])
  end

  def create
    plan = Plan.create(name: params[:plan][:name], user_id: current_user.id)
    RecipePlan.create(recipe_id: params[:plan][:recipe_id], plan_id: plan.id)
    redirect_to plan_path(plan)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  autocomplete :recipe, :name, :full => true
  def index
    @recipes = Recipe.all
  end

  def show
    @plan = Plan.new
    @my_recipe = Recipe.find(params[:id])
    @my_recipe_ingredients = Recipe.find(params[:id]).ingredients
    @ingredient_amount = Recipe.find(params[:id]).recipe_ingredients
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])

    if user && user.authenticate(params[:password])

      session[:user_id] = user.id
      redirect_to '/recipes'
    else
      redirect_to '/users/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/recipes", alert: "User created successfully."
    else

      render "new"
    end
  end

  private
  def user_params
    params.permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/recipe_plans_helper.rb
module RecipePlansHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<div class="main">
  <div class="wrapper">
    <h1>Suggest recipes</h1>
    <div class="form">
      <%= form_tag(suggestion_path, method: :get) do %>
        <div class="ingredient-form-input">
          <%= label_tag 'Ingredient 1'%>
          <%= autocomplete_field_tag 'ingredient1', '', autocomplete_ingredient_name_ingredients_path %>
        </div>
        <div class="ingredient-form-input">
          <%= label_tag 'Ingredient 2'%>
          <%= autocomplete_field_tag 'ingredient2', '', autocomplete_ingredient_name_ingredients_path %>
        </div>
        <div class="ingredient-form-input">
          <%= label_tag 'Ingredient 3'%>
          <%= autocomplete_field_tag 'ingredient3', '', autocomplete_ingredient_name_ingredients_path %>
        </div>
        <div class="ingredient-form-input">
          <%= label_tag 'Ingredient 4'%>
          <%= autocomplete_field_tag 'ingredient4', '', autocomplete_ingredient_name_ingredients_path %>
        </div>
        <div class="ingredient-form-input">
          <%= label_tag 'Ingredient 5'%>
          <%= autocomplete_field_tag 'ingredient5', '', autocomplete_ingredient_name_ingredients_path %>
        </div>
        <div class="form-input submit-btn">
          <%= submit_tag 'Suggest recipe'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/recipe_suggestion.html.erb
<div class="main">
  <div class="wrapper">
    <h1>Suggest recipes</h1>
    <div class="recipe-suggest-container">
    <% @recipe_sort.each do |recipe| %>
      <div class="recipe-suggest-item">
      <!-- add links -->
      <%= recipe.first %>
      </div>
    <% end %>
    </div>
  </div>
</div>