config/routes.rb
Rails.application.routes.draw do

  get 'users/login' => 'sessions#new'
  post 'users/login' => 'sessions#create'
  delete 'users/logout' => 'sessions#destroy'
  get 'users/new' => 'users#new'
  post 'users/new' => 'users#create'
  post 'recipes/:id' => 'recipe_plans#create', as: 'recipe_plans'
  get 'suggestion' => 'suggestions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes do
    get :autocomplete_recipe_name, :on => :collection
  end
  resources :shopping_lists, only: [:index, :show, :create]
  resources :plans, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipe_plans, only: [:create, :destroy]
  get "/", to: 'home#index'

  resources :ingredients, only: [:index, :show] do
    get :autocomplete_ingredient_name, :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_one :shopping_list
  has_many :recipe_plans
  has_many :recipes, through: :recipe_plans
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_plans
  has_many :plans, through: :recipe_plans

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe_plan.rb
class RecipePlan < ApplicationRecord
  belongs_to :plan
  belongs_to :recipe
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :plans
  has_many :shopping_lists
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    end

    @current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = current_user.plans.all
  end

  def show
    @my_plan = current_user.plans.find(params[:id])
  end

  def create
    plan = Plan.create(name: params[:plan][:name], user_id: current_user.id)
    RecipePlan.create(recipe_id: params[:plan][:recipe_id], plan_id: plan.id)
    redirect_to plan_path(plan)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  autocomplete :recipe, :name, :full => true
  def index
    @recipes = Recipe.all
  end

  def show
    @plan = Plan.new
    @my_recipe = Recipe.find(params[:id])
    @my_recipe_ingredients = Recipe.find(params[:id]).ingredients
    @ingredient_amount = Recipe.find(params[:id]).recipe_ingredients
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])

    if user && user.authenticate(params[:password])

      session[:user_id] = user.id
      redirect_to '/recipes'
    else
      redirect_to '/users/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/recipes", alert: "User created successfully."
    else

      render "new"
    end
  end

  private
  def user_params
    params.permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/recipe_plans_helper.rb
module RecipePlansHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/plans/index.html.erb
<div class="main">
  <div class="wrapper">
    <div class="heading">
      <h1>MyPlans</h1>
    </div>
    <div class="plans-section">
      <% @plans.each do |plan| %>
        <div class="plan-single">
          <tr>
            <td><a href="/plans/<%= plan.id %>" ><%= plan.name %></a></td>
          </tr>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="main">
  <div class="wrapper">
    <div class="heading">
      <h1>MyPlan</h1>
    </div>
    <h2><%= @my_plan.name %></h2>
    <div class="plan-container">
      <div class="create-btn">
        <button>
          <%= link_to "Generate ShoppingList", shopping_lists_path(@my_plan), method: :post %>
        </button>
      </div>
      <div class="plan-list">
        <% @my_plan.recipe_plans.each do |recipe_plan| %>
        <div class="plan-list-item">
          <% recipe = recipe_plan.recipe %>
          <p>
            <%= button_to "X", {:controller => :recipe_plans, :action => 'destroy', :id => recipe_plan.id }, class: 'delete-me', :method => :delete %>
            <%= recipe.name %>
          </p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="main">
  <div class="wrapper">
    <div class="recipes-container">
      <div class="heading">
        <h1>Recipes</h1>
      </div>
      <div class="recipes-section">
        <% @recipes.each do |recipe| %>
          <div class="recipe-single">
              <a href="/recipes/<%= recipe.id %>" >
                <%= recipe.name %>
                <img src=<%= recipe.avatar.url %> alt="">
              </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="main">
  <div class="wrapper">
    <div>
      <h3><%= @my_recipe.name %></h3>
    </div>
    <div>
      <img src=<%= @my_recipe.avatar.url %> alt="">
    </div>
    <div>
      <h3>Ingredients</h3>
      <div class="recipe-ingredients">
        <div class="ingredients-amount">
          <% @ingredient_amount.each do |amount| %>
            <p>
              <%= amount.amount %>
            </p>
          <% end %>
        </div>
        <div class="ingredients">
          <% @my_recipe_ingredients.each do |recipe_ingredient| %>
            <p>
              <%= recipe_ingredient.name %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="preparation">
      <h3>Preparation</h3>
      <p><%= @my_recipe.description %></p>
    </div>
    <div class="create-plan">
      <%= form_for @plan do |f| %>
        <%= f.hidden_field :recipe_id, value: @my_recipe.id %>
        <%= f.text_field :name %>
        <%= f.submit "Create new MyPlan and add recipe!" %>
      <% end %>
    </div>
    <% if current_user.plans.any? %>
    <div class="add-to-plan">
        <%= form_tag recipe_plans_path do %>
          <%= hidden_field_tag :recipe_id, @my_recipe.id %>
          <%= select_tag :plan_id, options_from_collection_for_select(current_user.plans, "id", "name") %>
      <!-- make inactive if there is no plan yet -->
          <%= submit_tag "Pick existing MyPlan and add recipe!" %>
        <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="wrapper">
    <div class="heading">
      <h1>New user</h1>
    </div>
    <div>
        <% if @user.errors.any? %>
          <div id="error_explanation">
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </div>
        <% end %>
    </div>
    <div>
      <div class="form">
        <%= form_tag '/users/new' do %>
          <div class="form-input">Name: <%= text_field_tag :name %></div>
          <div class="form-input">Password: <%= password_field_tag :password %></div>
          <div class="form-input">Password Confirmation: <%= password_field_tag :password_confirmation %></div>
          <div class="form-input submit-btn"><%= submit_tag "Submit" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>